package com.bx.admin.service;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface BaseService <T,E>{
	
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    long countByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    int deleteByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    List<T> selectByExampleWithBLOBs(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    List<T> selectByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    T selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    int updateByExampleSelective(@Param("record") T record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") T record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    int updateByExample(@Param("record") T record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    int updateByPrimaryKey(T record);

}
