package com.bx.admin.dao.mapper;

import com.bx.admin.dao.BaseMapper;
import com.bx.admin.dao.model.Resources;
import com.bx.admin.dao.model.ResourcesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourcesMapper extends BaseMapper<Resources, ResourcesExample>{

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	long countByExample(ResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	int deleteByExample(ResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	int insert(Resources record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	int insertSelective(Resources record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	List<Resources> selectByExampleWithBLOBs(ResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	List<Resources> selectByExample(ResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	Resources selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Resources record, @Param("example") ResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") Resources record, @Param("example") ResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	int updateByExample(@Param("record") Resources record, @Param("example") ResourcesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	int updateByPrimaryKeySelective(Resources record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	int updateByPrimaryKeyWithBLOBs(Resources record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resources
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	int updateByPrimaryKey(Resources record);
	
	
	List<Resources> selectCollectResoureces(@Param("type")Integer type);
}