server:
  port: 80
  
spring:
  datasource:
    url: jdbc:mysql://47.106.118.9:3306/dwz?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/admin/
mybatis:
  mapper-locations:
  - classpath:com/bx/admin/dao/mapper/xml/*Mapper.xml    
  
logging:
  file: log/admin.log
  level:
    org.springframework: info
    com.bx.admin.dao: debug
    
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
    
