package com.bx.admin.dao.model;

import java.util.Date;
import java.util.List;

public class Resources {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.id
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.sn
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	private String sn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.title
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.url
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.status
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.type
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.insert_date
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	private Date insertDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.update_date
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	private Date updateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.parent_id
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resources.content
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.id
	 * @return  the value of resources.id
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	
	private List<Resources> sonResourcesList;
	
	
	public List<Resources> getSonResourcesList() {
		return sonResourcesList;
	}

	public void setSonResourcesList(List<Resources> sonResourcesList) {
		this.sonResourcesList = sonResourcesList;
	}

	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.id
	 * @param id  the value for resources.id
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.sn
	 * @return  the value of resources.sn
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public String getSn() {
		return sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.sn
	 * @param sn  the value for resources.sn
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public void setSn(String sn) {
		this.sn = sn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.title
	 * @return  the value of resources.title
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.title
	 * @param title  the value for resources.title
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.url
	 * @return  the value of resources.url
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.url
	 * @param url  the value for resources.url
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.status
	 * @return  the value of resources.status
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.status
	 * @param status  the value for resources.status
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.type
	 * @return  the value of resources.type
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.type
	 * @param type  the value for resources.type
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.insert_date
	 * @return  the value of resources.insert_date
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public Date getInsertDate() {
		return insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.insert_date
	 * @param insertDate  the value for resources.insert_date
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.update_date
	 * @return  the value of resources.update_date
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.update_date
	 * @param updateDate  the value for resources.update_date
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.parent_id
	 * @return  the value of resources.parent_id
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.parent_id
	 * @param parentId  the value for resources.parent_id
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resources.content
	 * @return  the value of resources.content
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resources.content
	 * @param content  the value for resources.content
	 * @mbg.generated  Fri Apr 13 18:27:54 CST 2018
	 */
	public void setContent(String content) {
		this.content = content;
	}
}