package com.bx.admin.dao.model;

import java.util.Date;

public class RolesPermissions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_permissions.id
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_permissions.role_id
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_permissions.resoure_id
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    private Integer resoureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_permissions.resoure_name
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    private String resoureName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_permissions.role_name
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_permissions.permission
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles_permissions.create_date
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_permissions.id
     *
     * @return the value of roles_permissions.id
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_permissions.id
     *
     * @param id the value for roles_permissions.id
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_permissions.role_id
     *
     * @return the value of roles_permissions.role_id
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_permissions.role_id
     *
     * @param roleId the value for roles_permissions.role_id
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_permissions.resoure_id
     *
     * @return the value of roles_permissions.resoure_id
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    public Integer getResoureId() {
        return resoureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_permissions.resoure_id
     *
     * @param resoureId the value for roles_permissions.resoure_id
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    public void setResoureId(Integer resoureId) {
        this.resoureId = resoureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_permissions.resoure_name
     *
     * @return the value of roles_permissions.resoure_name
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    public String getResoureName() {
        return resoureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_permissions.resoure_name
     *
     * @param resoureName the value for roles_permissions.resoure_name
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    public void setResoureName(String resoureName) {
        this.resoureName = resoureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_permissions.role_name
     *
     * @return the value of roles_permissions.role_name
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_permissions.role_name
     *
     * @param roleName the value for roles_permissions.role_name
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_permissions.permission
     *
     * @return the value of roles_permissions.permission
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_permissions.permission
     *
     * @param permission the value for roles_permissions.permission
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles_permissions.create_date
     *
     * @return the value of roles_permissions.create_date
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles_permissions.create_date
     *
     * @param createDate the value for roles_permissions.create_date
     *
     * @mbg.generated Thu Apr 12 17:54:14 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}